# Generated by Django 3.2 on 2021-04-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anti_tb_app', '0003_rename_userid_survey_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='answer',
            new_name='answers',
        ),
        migrations.AddField(
            model_name='survey',
            name='knowledge',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
