# Generated by Django 3.2 on 2021-04-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anti_tb_app', '0005_survey_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='answers',
            field=models.CharField(max_length=200),
        ),
    ]
