# Generated by Django 3.2 on 2021-04-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anti_tb_app', '0006_alter_survey_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='answers',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='knowledge',
            field=models.CharField(max_length=200),
        ),
    ]
